# Generated by Django 5.2 on 2025-04-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_rename_name_contact_first_name_contact_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='Unbekannt'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='medium'),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.CharField(null=True),
        ),
    ]
