# Generated by Django 5.2 on 2025-04-25 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_rename_assigned_task_assigned_to_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='kanban',
            field=models.CharField(default='to-do'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(default='sales'),
        ),
    ]
